# Generated by Django 5.2.6 on 2025-09-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('ngo', 'NGO'), ('company', 'Private Company'), ('personal', 'Personal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Start'), ('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=16),
        ),
    ]
